
version: '3.7'

services:
  dogfind:
    build:
      context: .
      dockerfile: Dockerfile
      target: base
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
      - ./nodemon.json:/app/nodemon.json
    container_name: dogfind
    expose:
      - '3000'
    ports:
      - '3000:3000'
      - '9229:9229' # for debugging
    command: npm run dev